// AUTO-GENERATED by scripts/sync-stats.mjs — do not edit by hand.
// Last sync: 2026-06-03
export const siteStats = {
  packages: 32,
  pdfs: 2293,
  dwgs: 697,
  hours: 6000,
  nextOpening: "Q3 26",
  updatedAt: "2026-06-03",
} as const;
