// scripts/sync-stats.mjs
// Monthly stats sync — scans the local architecture archive and updates lib/siteStats.ts.
//
// Usage:
//   node scripts/sync-stats.mjs --dry-run   # compute + print only (no writes)
//   node scripts/sync-stats.mjs             # compute + write lib/siteStats.ts if changed
//   node scripts/sync-stats.mjs --deploy    # + git commit/push + Contabo deploy
//
// Override the archive location with KRAIN_ARCHIVE_DIR.
//
// Counting (honest about reliability):
//   packages = numbered job folders             -> RELIABLE
//   pdfs     = every .pdf in those folders       -> ACCURATE (raw count)
//   dwgs     = every .dwg in those folders        -> ACCURATE (raw count)
//   hours    = (pdfs + dwgs) * HOURS_PER_FILE     -> A GUESS (tunable factor below)

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "..");
const ARCHIVE = process.env.KRAIN_ARCHIVE_DIR || "C:/Users/kepne/OneDrive/Documents/#Architecture";
const DATA_FILE = path.join(REPO, "lib", "siteStats.ts");

const DRY = process.argv.includes("--dry-run");
const DEPLOY = process.argv.includes("--deploy");

const NEXT_OPENING = "Q3 26"; // static; edit by hand when it changes
const HOURS_PER_FILE = 2; // a guess — avg hours per drawing file (pdf/dwg). Tune to taste.
const HOURS_ROUND = 100; // round the hours guess to the nearest N for a clean headline number

// PDFs that are clearly not drawings (kept for the optional drawing-only count).
const NON_DRAWING =
  /invoice|manual|brochure|approved|quote|fee|terms|agreement|admin|certificate|warranty|receipt|statement|purchase\s*order|minutes|meeting|\bpo\b/i;

function listJobDirs() {
  return fs
    .readdirSync(ARCHIVE, { withFileTypes: true })
    .filter((e) => e.isDirectory() && /^\d{1,3}\b/.test(e.name.trim()))
    .map((e) => e.name);
}

function walkFiles(dir, acc) {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      walkFiles(full, acc);
    } else if (/\.pdf$/i.test(e.name)) {
      acc.pdfs++;
      if (!NON_DRAWING.test(e.name)) acc.pdfsDrawing++;
    } else if (/\.dwg$/i.test(e.name)) {
      acc.dwgs++;
    }
  }
  return acc;
}

function compute() {
  const jobs = listJobDirs();
  const acc = { pdfs: 0, pdfsDrawing: 0, dwgs: 0 };
  for (const j of jobs) walkFiles(path.join(ARCHIVE, j), acc);
  const hours = Math.round(((acc.pdfs + acc.dwgs) * HOURS_PER_FILE) / HOURS_ROUND) * HOURS_ROUND;
  return { packages: jobs.length, ...acc, hours };
}

function readCurrent() {
  try {
    const txt = fs.readFileSync(DATA_FILE, "utf8");
    const n = (k) => {
      const m = txt.match(new RegExp(k + ":\\s*(\\d+)"));
      return m ? Number(m[1]) : null;
    };
    return { packages: n("packages"), pdfs: n("pdfs"), dwgs: n("dwgs"), hours: n("hours") };
  } catch {
    return null;
  }
}

function writeData(s, isoDate) {
  const out =
    `// AUTO-GENERATED by scripts/sync-stats.mjs — do not edit by hand.\n` +
    `// Last sync: ${isoDate}\n` +
    `export const siteStats = {\n` +
    `  packages: ${s.packages},\n` +
    `  pdfs: ${s.pdfs},\n` +
    `  dwgs: ${s.dwgs},\n` +
    `  hours: ${s.hours},\n` +
    `  nextOpening: ${JSON.stringify(NEXT_OPENING)},\n` +
    `  updatedAt: ${JSON.stringify(isoDate)},\n` +
    `} as const;\n`;
  fs.writeFileSync(DATA_FILE, out, "utf8");
}

function sh(cmd, opts = {}) {
  return execSync(cmd, { cwd: REPO, stdio: opts.inherit ? "inherit" : "pipe" });
}

// ── main ──────────────────────────────────────────────
const isoDate = new Date().toISOString().slice(0, 10);

if (!fs.existsSync(ARCHIVE)) {
  console.error(`[sync-stats] Archive not found: ${ARCHIVE}`);
  process.exit(1);
}

const s = compute();
const current = readCurrent();

console.log(`[sync-stats] ${isoDate}  archive: ${ARCHIVE}`);
console.log(`  packages       : ${s.packages}${current ? ` (was ${current.packages})` : ""}`);
console.log(`  pdfs (all)     : ${s.pdfs}${current ? ` (was ${current.pdfs})` : ""}`);
console.log(`  pdfs (drawings): ${s.pdfsDrawing}   [excludes invoices/manuals/etc.]`);
console.log(`  dwg files      : ${s.dwgs}${current ? ` (was ${current.dwgs})` : ""}`);
console.log(`  hours (guess)  : ${s.hours}   [= (${s.pdfs}+${s.dwgs}) x ${HOURS_PER_FILE}, rounded to ${HOURS_ROUND}]`);

if (DRY) {
  console.log("[sync-stats] dry-run; no files changed.");
  process.exit(0);
}

const changed =
  !current ||
  current.packages !== s.packages ||
  current.pdfs !== s.pdfs ||
  current.dwgs !== s.dwgs ||
  current.hours !== s.hours;

if (!changed) {
  console.log("[sync-stats] no change; nothing to do.");
  process.exit(0);
}

writeData(s, isoDate);
console.log(`[sync-stats] wrote ${DATA_FILE}`);

if (!DEPLOY) {
  console.log("[sync-stats] data updated locally. Re-run with --deploy to publish.");
  process.exit(0);
}

try {
  sh(`git add lib/siteStats.ts`);
  sh(`git commit -m "🤖 chore: monthly stats sync (${s.packages} pkgs / ${s.pdfs} pdfs / ${s.dwgs} dwgs / ~${s.hours}h)"`);
  sh(`git push origin main`);
  console.log("[sync-stats] pushed to main.");
  sh(
    `ssh contabo "/opt/stack/bin/deploy-site.sh --site-dir /opt/stack/sites/krain-studio --service krain --branch main --healthcheck-url https://www.krain.studio"`,
    { inherit: true }
  );
  console.log("[sync-stats] deployed.");
} catch (err) {
  console.error("[sync-stats] deploy step failed:", err.message);
  process.exit(1);
}
